module.exports = [
  "initial: home",
  "",
  "# data 是所有页面都能使用的共享数据。",
  "data:",
  "  items:",
  "    - title: \"第一项\"",
  "      description: \"这是一个示例项目\"",
  "      done: false",
  "",
  "pages:",
  "  home:",
  "    title: \"首页\"",
  "    state:",
  "      selected: 0",
  "      notice: \"\"",
  "    layout:",
  "      type: column",
  "      padding: [1, 2]",
  "      children:",
  "        - type: text",
  "          value: \"我的 Page TUI 页面\"",
  "          style: title",
  "        - type: panel",
  "          title: \"项目列表\"",
  "          flex: true",
  "          child:",
  "            type: list",
  "            items: data.items",
  "            selected: state.selected",
  "            label: \"{{ item.title }}\"",
  "            description: \"{{ item.description }}\"",
  "            emptyText: \"暂无项目\"",
  "        - type: text",
  "          bind: state.notice",
  "          visible: state.notice",
  "          style: success",
  "        - type: text",
  "          value: \"↑/↓ 选择   Enter 查看   q 退出\"",
  "          style: muted",
  "    keys:",
  "      up:",
  "        - move:",
  "            path: state.selected",
  "            by: -1",
  "            list: data.items",
  "      down:",
  "        - move:",
  "            path: state.selected",
  "            by: 1",
  "            list: data.items",
  "      enter:",
  "        - push:",
  "            page: detail",
  "            params:",
  "              item:",
  "                itemAt:",
  "                  list: data.items",
  "                  index: state.selected",
  "",
  "  detail:",
  "    title: \"详情\"",
  "    layout:",
  "      type: column",
  "      padding: [1, 2]",
  "      children:",
  "        - type: text",
  "          value: \"详情页面\"",
  "          style: title",
  "        - type: text",
  "          template: \"标题：{{ params.item.title }}\"",
  "        - type: text",
  "          template: \"状态：{{ if(params.item.done, '已完成', '未完成') }}\"",
  "        - type: text",
  "          value: \"Esc 返回\"",
  "          style: muted",
  "    keys:",
  "      escape:",
  "        - pop",
  ""
].join("\n");
